import type { PoolClient } from 'pg';

import { allShardRanges, shardSequenceName } from '@url-shortener/shared';

import { apiConfig } from '../../config.js';

/**
 * Moves link id allocation from one global identity column to one sequence per
 * shard, each confined to its own contiguous block of the short-code space.
 *
 * The identity is dropped rather than switched to `GENERATED BY DEFAULT`: with
 * no default at all, any insert that forgets to supply an id fails loudly on the
 * NOT NULL constraint instead of silently allocating from a range that belongs
 * to another shard.
 *
 * Rows that already exist were issued by the old global sequence and sit at the
 * bottom of the space, which is shard 1's block, so shard 1 simply starts above
 * the highest id in use and no existing short code changes.
 */
export const migration = {
  id: '003_shard_id_sequences',
  async up(client: PoolClient): Promise<void> {
    await client.query('ALTER TABLE links ALTER COLUMN id DROP IDENTITY IF EXISTS');

    const highestId = await client.query<{ max: string | null }>('SELECT MAX(id)::text AS max FROM links');
    const nextFreeId = BigInt(highestId.rows[0]?.max ?? '0') + 1n;

    for (const range of allShardRanges(apiConfig.SHARD_COUNT)) {
      // Only shard 1 can contain pre-existing rows, so only it needs to skip
      // past them. Every other shard starts at the bottom of its own block.
      const startAt = range.start < nextFreeId && nextFreeId <= range.end ? nextFreeId : range.start;

      if (startAt > range.end) {
        throw new Error(`Shard ${String(range.shardId)} has no ids left to issue`);
      }

      await client.query(
        `CREATE SEQUENCE IF NOT EXISTS ${shardSequenceName(range.shardId)}
           AS BIGINT
           MINVALUE ${range.start.toString()}
           MAXVALUE ${range.end.toString()}
           START WITH ${startAt.toString()}
           NO CYCLE
           OWNED BY links.id`
      );
    }
  }
};
